import React from 'react';
import Header from '../components/Header';
import Footer from '../components/Footer';

const CancellationRefund: React.FC = () => {
  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col">
      <Header />
      <main className="flex-1 py-16 px-4 md:py-24">
        <div className="container max-w-4xl mx-auto">
          <h1 className="text-3xl md:text-4xl font-bold tracking-tight mb-8 text-center">Cancellation & Refund Policy</h1>
          <div className="prose prose-blue dark:prose-invert max-w-none bg-card border border-border/60 rounded-2xl p-6 md:p-10 shadow-soft space-y-6">
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Data fiduciary footer</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Cancellation & Refund Policy | helllo.ai</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Learn how subscriptions and cancellations work for Helllo AI paid plans. Monthly billing via Stripe (USD) or Razorpay (INR for India), cancel anytime, no refunds — credits remain for 2-month carry-forward.</p>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">cancellation policy, refund policy, helllo.ai billing, subscription cancellation, Stripe billing, Razorpay billing</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">https://www.helllo.ai/cancellation-refund</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">How subscriptions and cancellations work for Helllo AI paid plans billed through Stripe (USD) or Razorpay (INR for India). No refunds — use credits during the 2-month carry-forward period.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Last updated: March 2026</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">This policy describes how subscriptions and cancellations work for Helllo AI (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;) when you purchase a paid plan through our application.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">No monetary refunds are offered</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">for self-serve subscription payments.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Subscriptions</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Paid plans are</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">monthly subscriptions</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">. Billing currency and payment processor depend on your account billing country.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">International accounts:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">payments are processed through</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Stripe</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">United States Dollars (USD)</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">. Your bank or card issuer may apply currency conversion or foreign transaction fees depending on your payment method and country.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Accounts in India:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Razorpay</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Indian Rupees (INR)</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">. Self-serve checkout is available for accounts with</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">as the billing country.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Each successful payment grants</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">plan credits</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">for that billing cycle. Custom plans follow the credits shown on your Billing page.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">New accounts may receive a</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">one-time signup credit</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">grant (currently</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">500 credits</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">), separate from subscription credits.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Enterprise</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">and custom commercial terms are agreed separately with our sales team.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">How to cancel</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">You can cancel from the application:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Console → Profile → Billing → Current subscription → Cancel subscription</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">When you cancel:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">list-decimal list-inside text-muted-foreground space-y-2 mb-4</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Your subscription</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">remains active until the end of your current billing period</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">(shown as</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Access until</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">in the app).</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">You will not be charged again</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">after that date.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Credits already added to your account for the current period remain available</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">until they expire under our credit carry-forward rules (see</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">#credit-expiry</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Credit expiry</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Cancellation does</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">not</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">delete your account or remove access to historical invoices in the Billing → Invoices tab.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Issued tax invoices are not voided</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">by cancellation. Invoice details reflect what was captured at issue time.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">We do</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">currently offer self-serve</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">immediate cancellation</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">(stop access now) for voluntary cancellation. If you need your subscription ended immediately, contact us at</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">What you cannot do in the app today</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Undo cancel</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">— there is no &quot;resume subscription&quot; button. You can</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">subscribe again</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">from the Billing page.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Change plan</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">while a cancellation is scheduled — use</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">on the new plan instead.</p>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">is only available for an active renewing subscription.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Resubscribing and plan changes</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Resubscribe after cancel</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">If you scheduled cancellation, you may</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">subscribe again at any time</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">from the Billing page, including</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">before</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">your current access period ends.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">When a new subscription payment succeeds:</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Your new plan and billing period start from that payment date.</p>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Your previous subscription will not renew and is retired according to our billing integration with Stripe or Razorpay, depending on your payment processor.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Change plan (while subscribed)</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">If you have an active renewing subscription, you may</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">on the Billing page.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Your</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">current plan stays active until payment for the new plan succeeds</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">You are</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">not charged for both plans</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">in parallel for the same period.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Plan changes are</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">not prorated</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">in the application — the new plan&apos;s full monthly price applies on successful checkout.</p>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">On successful payment for the new plan, the previous subscription is cancelled in Stripe or Razorpay (this is an immediate cancellation of the old subscription, not end-of-period cancellation).</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">credit-expiry</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Credit expiry (not a refund)</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Subscription payments add credits to your account wallet via our credit ledger.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Credits are stored in</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">grant buckets</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">with an expiry date.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">By default, credits expire after</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">2 months</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">from the date they are granted (</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">text-sm bg-muted px-1 py-0.5 rounded</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">credit_carry_forward_months</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">on your account). Some accounts may have a different carry-forward setting set by us.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Cancelling your subscription does not remove credits</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">already granted for the paid period.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Cancelling does not extend</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">credit expiry. Unused credits expire automatically after the carry-forward window.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">After your subscription ends, you may continue using</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">remaining credits</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">until they expire or are consumed by usage.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Refunds</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">No refund will be made</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">for self-serve subscription payments, whether billed through</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Stripe (USD)</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Razorpay (INR)</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">. All subscription charges are</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">final and non-refundable</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">How to Initiate a Refund Request</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">accept monetary refund requests for self-serve subscriptions. Refunds are not available through the Billing UI, self-serve APIs, or by email.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">cancel future billing</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">, use the in-app cancellation flow:</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">For billing questions only (invoices, payment status, receipt access through Stripe or Razorpay, or account access), contact</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">. Billing support does</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">include refund processing.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Conditions for Refund Eligibility</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">under any condition for self-serve subscriptions (Stripe or Razorpay), including voluntary cancellation, change of mind, partial use of a billing period, or unused credits.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">In place of a refund, each successful payment grants</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">to your account, whether you paid in USD through Stripe or INR through Razorpay. You are expected to</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">use those credits</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">during the</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">2-month carry-forward period</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">described in</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Credits from each successful payment remain available until they expire (default:</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">from the grant date)</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Cancelling your subscription does</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">remove credits already granted — you may continue using them until they expire or are consumed</p>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Unused credits expire automatically after the carry-forward window; they are not converted to cash or refunded in USD, INR, or any other currency</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Enterprise and custom contracts may follow separate agreement terms via</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">mailto:sales@helllo.ai</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">sales@helllo.ai</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Refund Processing Timeline</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Because we do</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">issue monetary refunds, there is</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">no refund processing timeline</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">for self-serve subscriptions, whether processed through Stripe or Razorpay.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">The value of your payment is applied</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">immediately</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">upon successful charge, when plan credits are granted to your account. Credits remain usable for</p>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">from the grant date under our carry-forward policy, regardless of subscription cancellation.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Failed payments</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">If a</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">renewal payment fails</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">, your subscription may enter a</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">past due</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">state while Stripe or Razorpay retries collection according to its rules.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">You may still</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">from the Billing page while past due.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">New cycle credits are not granted</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">until a payment succeeds.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Credits from the</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">last successful</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">charge are not automatically removed when a renewal fails.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Billing details and invoices</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Complete</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Billing & invoicing details</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">(legal name, address, email, phone, and GSTIN where applicable for India) before subscribing so receipts and invoices reflect your business information.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Updates to billing details apply to</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">future</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">invoices and charges, not invoices already issued.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Stripe (international):</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">payment receipts and invoices are provided through Stripe. Charges appear in</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">USD</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Razorpay (India):</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">hosted invoices and PDFs are provided through Razorpay. Charges appear in</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">INR</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Your billing history and invoice links are available in the app under Billing → Invoices.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Enterprise plans</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Custom and Enterprise plans are sold through</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">. Cancellation, refunds, and contract terms for those agreements are governed by your</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">order form or contract</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">, not this self-serve policy.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Product access after cancellation</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">While your subscription status is</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">, your account is treated as having a paid subscription for certain product limits (for example, Spark website scan quotas).</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">After the subscription status becomes</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">cancelled</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">at the end of your paid period:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Monthly credit grants stop</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Free-tier or credit-based limits</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">apply where configured (for example, usage gated by available credits or free-plan quotas).</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">account and data</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">remain unless you request account deletion separately.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Changes to this policy</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">We may update this policy from time to time. The version published on our website applies to billing after the update date. Material changes may also be communicated by email or in-app notice where appropriate.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Topic</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">py-2 pr-4</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Billing support</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">py-2</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Enterprise sales</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Summary</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Monthly billing</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">— Stripe (USD) for international accounts; Razorpay (INR) for accounts in India.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Cancel anytime</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">— access continues until the end of the paid period; no renewal after that.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Credits</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">from each payment remain until they expire under carry-forward rules (default: 2 months).</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">No refunds</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">— use plan credits during the 2-month carry-forward period; unused credits expire and are not refunded.</p>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">— custom terms via sales.</p>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Redirecting to console...</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">404</h2>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default CancellationRefund;
