import React from 'react';
import Header from '../components/Header';
import Footer from '../components/Footer';

const Privacy: React.FC = () => {
  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col">
      <Header />
      <main className="flex-1 py-16 px-4 md:py-24">
        <div className="container max-w-4xl mx-auto">
          <h1 className="text-3xl md:text-4xl font-bold tracking-tight mb-8 text-center">Privacy Policy</h1>
          <div className="prose prose-blue dark:prose-invert max-w-none bg-card border border-border/60 rounded-2xl p-6 md:p-10 shadow-soft space-y-6">
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Website</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Privacy Policy | helllo.ai - GDPR & DPDP Compliant</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Privacy Policy for helllo.ai - Learn how we collect, use, and protect your personal information in compliance with GDPR and DPDP. Your privacy is our priority.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">privacy policy, GDPR compliance, DPDP, data protection, helllo.ai privacy</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">https://www.helllo.ai/privacy</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Privacy Policy | helllo.ai</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Learn how helllo.ai protects your personal information in compliance with GDPR and DPDP regulations.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Last updated: June 15, 2026</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">1. Introduction</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Perceptory AI Labs Private Limited, operating the helllo.ai platform (&quot;Helllo.ai&quot;, &quot;we&quot;, &quot;our&quot;, or &quot;us&quot;), provides AI-powered voice and customer engagement services to businesses and organizations. This Privacy Policy explains what personal information we collect, why we collect it, how we use and share it, and the choices available to you.</p>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">We are committed to protecting personal information and complying with applicable privacy laws, including the Digital Personal Data Protection Act, 2023 (DPDP) in India and the General Data Protection Regulation (GDPR) where applicable.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Data Fiduciary Information</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">For the purposes of applicable privacy laws, Perceptory AI Labs Private Limited is the data fiduciary responsible for processing personal information described in this policy.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Grievance Officer</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">If you have concerns about how we handle your personal information, you may contact our Grievance Officer:</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Name:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Sandilya Konduri</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Email:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">mailto:grievance@helllo.ai</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">grievance@helllo.ai</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Response Time:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Acknowledgement within 48 hours</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Resolution within 30 calendar days</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">2. What We Collect and Why</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">We collect personal information to provide, secure, and improve our services. The table below summarizes the main categories of data we process.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">overflow-x-auto not-prose mb-6</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">thead</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Data Collected</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Purpose</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Required?</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Shared with Processors?</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Typical Retention</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">tbody</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Name</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">py-3 px-3</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Account creation and communication</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Yes, for account holders</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Yes, with service providers</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">While account is active + legal period</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Email Address</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Authentication and support</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Call routing and communication</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Often required for voice services</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Yes, with telecom and cloud providers</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Per customer configuration</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Voice Recordings</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Call handling, quality assurance and analytics</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Depends on service configuration</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Yes, with AI and cloud providers</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Call Transcripts</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">AI processing, summaries and workflow automation</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">CRM Data</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Customer relationship management</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Optional, when integrations are enabled</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Yes, with integrated CRM providers</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Conversation Metadata</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Service performance and analytics</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Collected automatically during use</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Yes, with analytics and cloud providers</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Up to 2 years in aggregated form</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Cookies</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Website functionality and analytics</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Necessary cookies only without consent; others require consent</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Yes, with cookie and analytics vendors</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Varies by cookie type</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Device Information</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Security, fraud prevention and diagnostics</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Yes, with security and cloud providers</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Short-term logs; longer if needed for security</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">We only collect information that is reasonably necessary for the purposes described above. Where information is not required to use a feature, you may choose not to provide it, though some features may not work without it.</p>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">We do not sell personal information. We share information with trusted third-party processors only as needed to deliver our services, and we require them to protect that information under contractual obligations.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">AI-Assisted Services</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Helllo.ai provides AI-powered communication, automation and customer engagement services. To provide these services, certain information may be processed by artificial intelligence systems.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Examples include:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Voice call processing</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Call summaries</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Intent extraction</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Customer support automation</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Workflow execution</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Analytics and insights</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">AI-generated outputs may occasionally be inaccurate and should be reviewed where appropriate.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Call Recording and Transcription</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Calls handled through Helllo.ai may be recorded and transcribed.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Recordings and transcripts may be used for:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Service delivery</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Quality assurance</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Customer support</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Training and improvement of customer workflows</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Compliance and dispute resolution</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Analytics and reporting</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Customers are responsible for obtaining any legally required notices or consent from call participants.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Subprocessors and Service Providers</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Helllo.ai may engage trusted third-party service providers to deliver services. Examples include:</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">OpenAI</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">list-disc list-inside text-muted-foreground space-y-2 mb-6</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Purpose:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">AI model processing and language understanding</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Data Categories Processed:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Call transcripts, text inputs, conversation content and related metadata</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Google Cloud</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Cloud hosting, infrastructure, storage and security</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Account data, voice recordings, transcripts, logs and operational data</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">We contractually require service providers to implement appropriate security and confidentiality protections.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">gdpr</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">mb-8 scroll-mt-24</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">3. Legal Basis for Processing (GDPR)</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Where GDPR applies, we process personal information based on the following legal grounds:</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Contract Performance:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">To provide the services you or your organization have requested</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Legitimate Interest:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">To improve our services, maintain security, and prevent fraud</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Consent:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">For optional features, marketing communications, and non-essential cookies</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Legal Obligation:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">To comply with applicable laws and regulatory requirements</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">4. Information Sharing and Disclosure</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">We do not sell personal information. We may share information in these situations:</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Service Providers:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">With vendors who help us operate our platform (see Subprocessors above)</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Business Transfers:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">In connection with mergers, acquisitions, or asset sales</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Legal Requirements:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">When required by law or to protect rights, safety, and security</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">With Consent:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">When you or your organization has given explicit consent</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Security Measures</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Helllo.ai employs reasonable technical and organizational safeguards including:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">HTTPS/TLS encryption in transit</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Encryption of sensitive data where applicable</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Role-based access controls</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Authentication and authorization controls</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Infrastructure monitoring</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Backup and recovery procedures</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Incident response processes</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">No internet-based service can guarantee absolute security.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Data Retention</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">We retain personal information only for as long as necessary to:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Deliver services</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Meet legal obligations</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Resolve disputes</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Enforce agreements</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Retention periods may vary based on:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Customer configuration</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Service type</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Regulatory requirements</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Operational requirements</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">When information is no longer required, it is deleted, anonymized or securely destroyed.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Your Rights Under Applicable Privacy Laws</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Depending on your location, you may have the following rights regarding your personal information:</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Right to Access</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Request a copy of personal information we maintain.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Right to Correction</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Request correction of inaccurate or incomplete information.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Right to Erasure</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Request deletion of personal information, subject to legal and contractual obligations.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Right to Withdraw Consent</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Withdraw previously granted consent at any time.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Right to Grievance Redressal</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Raise concerns regarding processing of personal information.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Right to Nominate</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Nominate another individual to exercise rights on your behalf where permitted by law.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">How to Submit a Request</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Send an email to:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">mailto:privacy@helllo.ai</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">privacy@helllo.ai</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Subject:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Data Rights Request</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Include:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Full name</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Email address</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Description of request</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Any relevant account details</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Target response time:</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">30 calendar days.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">5. International Data Transfers</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Your information may be transferred to and processed in countries other than your own. We use appropriate safeguards for such transfers, including:</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Standard Contractual Clauses (SCCs) for EU data transfers</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Adequacy decisions by relevant authorities</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Certification schemes and codes of conduct</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">cookies</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Cookies and Tracking Technologies</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">We use cookies and similar technologies on our website. Cookiebot manages our cookie consent banner, which lets you accept all cookies, reject non-essential cookies, or customize your preferences. Non-essential cookies are not placed until you give consent.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">You can change or withdraw your consent at any time using</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Necessary</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Required for website operation, security, and basic functionality. These cookies cannot be disabled through our consent tool because the site would not work properly without them.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Analytics</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Used for understanding website usage and improving services. Analytics cookies are only placed after you consent to the Statistics category in Cookiebot.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Marketing</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Used for advertising, attribution, and third-party engagement tools such as scheduling widgets and chat widgets. Marketing cookies are only placed after you consent to the Marketing category.</p>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">We store a record of your consent choices so we can honor your preferences on future visits and when you withdraw consent.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Cookie Declaration</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">The table below is generated by Cookiebot and lists the cookies used on this website.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Children&apos;s Privacy</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Helllo.ai is intended for business users and organizations. Our services are not directed toward individuals under the age of 18. We do not knowingly collect personal information from children.</p>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">If we learn that personal information belonging to a child has been collected without appropriate authorization, we will take reasonable steps to delete such information. Parents or guardians who believe a child has provided personal information may contact</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Behavioral Tracking of Children</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Helllo.ai does not knowingly perform profiling, behavioral monitoring, targeted advertising or behavioral tracking of children.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Guardian Consent</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Where legally required, collection or processing of a child&apos;s personal information will occur only after obtaining appropriate consent from a parent, guardian or authorized representative.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Withdrawing Consent</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Users may withdraw consent at any time.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">To withdraw consent:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Use</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">cookie preference settings</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">Withdrawal of consent does not affect processing that occurred before withdrawal.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">6. Changes to This Privacy Policy</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">We may update this Privacy Policy from time to time. We will notify you of material changes by posting the updated policy on this page and updating the &quot;Last updated&quot; date. We encourage you to review this Privacy Policy periodically.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">Privacy Contact</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">For privacy-related questions:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">For grievances:</h2>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">For support:</h2>
            <p className="text-muted-foreground text-xs md:text-sm leading-relaxed">You also have the right to lodge a complaint with your local data protection authority if you believe we have not handled your personal information in accordance with applicable law.</p>
            <h2 className="text-lg md:text-xl font-bold mt-6 mb-3 text-foreground">mb-0</h2>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Privacy;
